server:
  port: 7083

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dibros?allowPublicKeyRetrieval=true&sslMode=DISABLED&useTimezone=true&serverTimezone=UTC
    username: root
    password: root

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7081/eureka/
jwt:
  config:
    type: signed